language: rust

rust:
- stable
- beta
- nightly

jobs:
  allow_failures:
  - rust: nightly
  fast_finish: true

deploy:
  provider: cargo
  token:
    secure: WGrQQT2AEtDAlJHLlsEilASahEaU8yu4wWOtOkL6lV2veJu0ETETipG5bdrgCBKpyhLX+m23PSwFugykEQILS5TdHmKzgGMMkXFGGreyWfZ2EfsG246MKq26AQIdjGoZxvqQ9zm3DtXCY/xRxmJqkn4j2qyl+ZvaOks1xKoKyJPGH71IODqZhQrMQ8LBCHIBQGRdKBdicHGiENbagAdGpV2mhwzkZ7EYw/69btVYGxyeNNiR1AIMNPiavwTRaRkk2avk+SN0sqg0dghrY89ec22v1ro46L3hxOJhsv7ciZOBEfORC7AfDzFvkCbyEKFB+8JuGInU7I7bKP7gTeRcl3l6aa5cqSOp9zlLM7tXgPsckgWlpsOL8DLz2oI03kCl/jH+M2F9SPGCCg1CpQ+vogoAd3tTVc+xVziHe7kTWyaS5dXP5AWC62WEO6Oh29Alny6EE+X5e+ApPiBOaaIf53gnnXc/f0Ob2rRp+SHl8mahNluKmoDvKenqXdsRvysPC34FpJqLXJeWyimUg5zFFXD/l1HTQ50JvvJANq62wIbjVby28bPzEUSjtfGA4efSjkk0eZIX9SYCiEB/We8HeN0EBeft0PLGE4gmNlDh42wWva6Pw+7mkOQvYsehGoHA5kh1VM3eYPj/NqqQUlvxxyE7qv5I6qflUr3zmwZ12P8=
  on:
    tags: true
